/**
 * api/admin-brief.js
 * POST /api/admin-brief
 *
 * Accepts a structured summary of the current dashboard state and returns
 * a streamed, receptionist-style briefing paragraph generated by Claude.
 *
 * Body: {
 *   practitioner: string,          // first name ("Cheree")
 *   greeting: string,              // "Good morning" / "Good afternoon" / "Good evening"
 *   todaySessions: Array<{ name, time }>,
 *   nextAppt: { name, day, time } | null,
 *   critCount: number,             // appointments missing invoice
 *   awaitingPayCount: number,      // invoices awaiting payment
 *   unlinkedCount: number,         // unlinked calendar events
 *   newEnquiries: number,
 * }
 *
 * Response: plain text stream (text/plain)
 */

import { isAuthed } from './_auth.js';

const ANTHROPIC_API = 'https://api.anthropic.com/v1/messages';
const MODEL         = 'claude-haiku-4-5';

export default async function handler(req, res) {
  if (!isAuthed(req)) return res.status(401).json({ error: 'Unauthorised' });
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) return res.status(503).json({ error: 'ANTHROPIC_API_KEY not configured' });

  const {
    practitioner = 'Cheree',
    todaySessions = [],
    nextAppt = null,
    critCount = 0,
    awaitingPayCount = 0,
    unlinkedCount = 0,
    newEnquiries = 0,
  } = req.body || {};

  // Build a compact data block for the prompt
  const lines = [];
  if (todaySessions.length === 0) {
    lines.push('No sessions today.');
  } else {
    lines.push('Sessions today: ' + todaySessions.map(function(s) {
      return s.name + (s.time ? ' at ' + s.time : '');
    }).join(', ') + '.');
  }
  if (nextAppt) {
    lines.push('Next appointment: ' + nextAppt.name
      + (nextAppt.day ? ' on ' + nextAppt.day : '')
      + (nextAppt.time ? ' at ' + nextAppt.time : '') + '.');
  } else {
    lines.push('No upcoming appointments scheduled.');
  }
  const issues = [];
  if (critCount > 0)        issues.push(critCount + ' appointment' + (critCount !== 1 ? 's' : '') + ' missing an invoice');
  if (awaitingPayCount > 0) issues.push(awaitingPayCount + ' invoice' + (awaitingPayCount !== 1 ? 's' : '') + ' awaiting payment');
  if (unlinkedCount > 0)    issues.push(unlinkedCount + ' unlinked calendar event' + (unlinkedCount !== 1 ? 's' : ''));
  if (issues.length)        lines.push('Admin: ' + issues.join(', ') + '.');
  else                      lines.push('No admin issues.');
  if (newEnquiries > 0)     lines.push(newEnquiries + ' new enquir' + (newEnquiries === 1 ? 'y' : 'ies') + ' in inbox.');
  else                      lines.push('No new enquiries.');

  const dataBlock = lines.join('\n');

  const prompt = `You are the front-desk assistant for ${practitioner} McGarry, a psychologist. When she opens her practice dashboard you give her a short, warm briefing — like a receptionist would say when she walks in the door. Write exactly 2–3 sentences in a natural, conversational tone. Do NOT use bullet points or lists. Do NOT start with a greeting (it's shown separately). Refer to clients by first name only. Be specific about the actual numbers and names — don't generalise.

Dashboard data:
${dataBlock}

Write only the briefing, nothing else.`;

  try {
    const upstream = await fetch(ANTHROPIC_API, {
      method:  'POST',
      headers: {
        'Content-Type':      'application/json',
        'x-api-key':         key,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model:      MODEL,
        max_tokens: 160,
        stream:     true,
        messages:   [{ role: 'user', content: prompt }],
      }),
    });

    if (!upstream.ok) {
      const err = await upstream.text();
      console.error('[admin-brief] Anthropic error', upstream.status, err);
      return res.status(502).json({ error: 'Upstream error' });
    }

    // Stream text/plain back to the browser
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Cache-Control', 'no-store');
    res.setHeader('Transfer-Encoding', 'chunked');

    const reader = upstream.body.getReader();
    const dec    = new TextDecoder();
    let   buf    = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += dec.decode(value, { stream: true });
      const lines = buf.split('\n');
      buf = lines.pop(); // keep incomplete last line

      for (const line of lines) {
        if (!line.startsWith('data: ')) continue;
        const raw = line.slice(6).trim();
        if (raw === '[DONE]') continue;
        try {
          const evt = JSON.parse(raw);
          if (evt.type === 'content_block_delta' && evt.delta?.type === 'text_delta') {
            res.write(evt.delta.text);
          }
        } catch (_) { /* ignore malformed SSE chunks */ }
      }
    }

    res.end();
  } catch (err) {
    console.error('[admin-brief]', err);
    if (!res.headersSent) res.status(500).json({ error: err.message });
    else res.end();
  }
}
